### ISSUE TITLE
OvertureStructure side property usage

### ISSUE THREAD

**Issue by pstkweb** [wanadev/WanaplanAPI#1]
I'm stuck on using the `side` property of the `OvertureStructure` class. 

I try to list all overtures by room, in order not to list twice doors (or windows) I wanted to associate an overture to the room in which it opens (where the hinges are). I thought the `side` property can help me but in fact not ; it always return the same value.

Here my test code :
```javascript
var floors = API.getFloors();
for (var i=0; i<floors.length; i++) {
    for (var j=0; j<floors[i].internalRooms.length; j++) {
        // Get floor rooms
        var room = floors[i].internalRooms[j];
        // Iterate room walls
        for (var k=0; k<room.walls.length; k++) {
            // Iterate wall overtures
            for (var l=0; l<room.walls[k].overtures.length; l++) {
                // room.walls[k].overtures[l].side must return -1 in 'Room 1' and 1 in 'Room 2'
                // TODO : Check if overture is in this room with WallPanes
            }
        }
    }
}
``` 

Is there some issue with this property or am I doing this wrong?

**Comment by CraigFeldspar** [comment]
Hello,

The documentation may not be accurate on this property. Can you try with the `hinge` property ?

**Comment by pstkweb** [comment]
Thank you for your response. 
Unfortunately `hinge` doesn't help it always returns the same value and as I understand this property say whether the overture opens to the left or to the right.

**Comment by perriern** [comment]
Hello,

The side property is 1 when the overture opens in the same direction as the wall normal (given by wall.getNormalVector() ) and -1 when it opens in the opposite direction. Which means it depends on how the points (0 and 1) of the wall are placed.

To know in which room an overture opens, I would do as follows:
- find the overture position in the canvas : wall.points[0].position + wall.getWallVector().scale(overture.position.x) (I know, not very logical)
- add wall.getNormalVector().scale(overture.side * wall.thickness +1) to the overture position to get a point just outside the overture
- use RoomComponent2D.isPointInRooms to find in which room the resulting point is situated

I hope this works for you.

**Comment by pstkweb** [comment]
Thanks @perriern,
I understood your proposal and give it a try with this formula :
```javascript
wall.points[0].position.add(
    wall.getWallVector().scale(overture.position.x)
 )
```
With for example, in my floor plan, `wall` an `WallStructure` with points *{x: 515, y: -415}* and *{x: -515, y: -415}* and `overture` an `OvertureStructure` of *Garage* type at *{x: 820, y: undefined}* it gives `{x: -843939.6525738948, y: -415}` which isn't on this wall. To get the right result I'd got to use the normalized wall vector :
```javascript
wall.points[0].position.add(
    wall.getWallVector().normalize().scale(overture.position.x)
 )
```

So the final formula is :
```javascript
wall.points[0].position.add(
    wall.getWallVector().normalize().scale(overture.position.x)
).add(
    wall.getNormalVector().scale(overture.side * (wall.thickness + 1))
)
```

My last question is : how can I get a `RoomComponent2D` instance in my component which is a child of `BaseComponent3D`?

**Comment by perriern** [comment]
Even if your component is 3D, you should have access to all the other components of wanaplan, 2D and 3D, through the API function : API.getComponent("RoomComponent2D")

**Comment by perriern** [comment]
Just thought of something, if you have several floors, `RoomComponent2D.isPointInRooms` will not work since it only operates on the rooms of the floor that was displayed in 2D (so if you change floors while in 3D, it is not updated).

In your case, it's better if you iterate on the internal rooms of your current floor and use:
`floorStructure.internalRooms[j].isPointIn(point)`
to find in which room the point is situated.

**Comment by pstkweb** [comment]
Thanks,
it works well. To summarize, here is the code to get the room in which an overture opens

- Given an overture :
```javascript
/**
 * Get the room in which an overture opens
 * 
 * @param OvertureStructure overture An overture
 *
 * @return RoomStructure|null        The room in which it opens or null
 */
function getRoomOvertureOpensIn(overture) {
    var wall = overture.getParentWall();
    var overturePosition = wall.points[0].position.add(
        wall.getWallVector().normalize().scale(overture.position.x)
    );
    var overtureOpenPosition = overturePosition.add(
        wall.getNormalVector().scale(overture.side * (wall.thickness + 1))
    );

    return API.getComponent("RoomComponent2D").isPointInRooms(
         overtureOpenPosition
    );
}
```

- Given a room :
```javascript
/**
 * Say whether an overture opens in a given room
 * 
 * @param OvertureStructure overture An overture
 * @param RoomStructure     room     A room
 *
 * @return boolean                   True if the room opens in the specified room
 */
function overtureOpensInRoom(overture, room) {
    var wall = overture.getParentWall();
    var overturePosition = wall.points[0].position.add(
        wall.getWallVector().normalize().scale(overture.position.x)
    );
    var overtureOpenPosition = overturePosition.add(
        wall.getNormalVector().scale(overture.side * (wall.thickness + 1))
    );

    return room.isPointInRooms(
         overtureOpenPosition
    );
}
```

I think we can close the issue as it solves my problem.
